### ISSUE TITLE
How to download the training dataset?

### ISSUE THREAD

**Issue by chenzhutian** [botaoye/OSTrack#10]
A silly question: where to download the specific training datasets?
Thanks!

**Comment by botaoye** [comment]
You can download the training datasets from their official website.

[LaSOT](https://github.com/HengLan/LaSOT_Evaluation_Toolkit)
[GOT-10k](http://got-10k.aitestunion.com/downloads)
[TrackingNet](https://github.com/SilvioGiancola/TrackingNet-devkit)
[COCO 2017](https://cocodataset.org/#download)

**Comment by chenzhutian** [comment]
Great! Downloading.
Thanks!
