### ISSUE TITLE
新手想请问一下关于训练的问题

### ISSUE THREAD

**Issue by rp7sv** [botaoye/OSTrack#107]
您在训练时用到了4张A100，请问用2张3090（不考虑时间）训练能达到论文所说的精度吗

**Comment by botaoye** [comment]
您好，当用不同GPU数量时，会造成batch size的改变。所以需要对应调整learning rate，是可以达到类似的精度的。

**Comment by aqizhoua** [comment]
@FogSue 大佬你好，我和你的情况类似，也是只有3090用于训练，请问你bseline的精度达到论文所说的了吗，我差了一两个点
