### ISSUE TITLE
Convert to ONNX and TensorRT

### ISSUE THREAD

**Issue by notnitsuj** [botaoye/OSTrack#12]
Hi, I'm trying to export this to ONNX to later convert to TensorRT for deployment. Even though this model is one-stream one-stage making it a lot easier to convert, I've encountered several warnings about converting a tensor to Python [integer, boolean, etc.]. The problems are with 2 `torch.linspace()` [here](https://github.com/botaoye/OSTrack/blob/f3c1aef4693307ebf698026a60d1b99a56a74711/lib/models/ostrack/vit_ce.py#L143-L146), and `math.ceil()` and the equality operator [here](https://github.com/botaoye/OSTrack/blob/f3c1aef4693307ebf698026a60d1b99a56a74711/lib/models/layers/attn_blocks.py#L28-L29). 

Below is one of the warnings:

```
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. 
We cant record the data flow of Python values, so this value will be treated as a constant in the future.
```

Has the author or anyone successfully converted this to ONNX and TensorRT? Can you guys give me some suggestions on how to work around this issue, or directly convert to TensorRT without facing this again?

Thanks a lot.

**Comment by botaoye** [comment]
1. For `torch.linspace`, you can replace it with `torch.arange`.
2. Maybe you can replace `math.ceil` with another function supported by ONNX or implement it on you own. 
3. `if lens_keep == lens_s:` can be simply removed since the inequality has already been guaranteed outside this function.

I'll also try to add ONNX/TensorRT support when I have time and pull requests are welcome.

**Comment by Stoooner** [comment]
> Hi, I'm trying to export this to ONNX to later convert to TensorRT for deployment. Even though this model is one-stream one-stage making it a lot easier to convert, I've encountered several warnings about converting a tensor to Python [integer, boolean, etc.]. The problems are with 2 `torch.linspace()` [here](https://github.com/botaoye/OSTrack/blob/f3c1aef4693307ebf698026a60d1b99a56a74711/lib/models/ostrack/vit_ce.py#L143-L146), and `math.ceil()` and the equality operator [here](https://github.com/botaoye/OSTrack/blob/f3c1aef4693307ebf698026a60d1b99a56a74711/lib/models/layers/attn_blocks.py#L28-L29).
> 
> Below is one of the warnings:
> 
> ```
> TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. 
> We cant record the data flow of Python values, so this value will be treated as a constant in the future.
> ```
> 
> Has the author or anyone successfully converted this to ONNX and TensorRT? Can you guys give me some suggestions on how to work around this issue, or directly convert to TensorRT without facing this again?
> 
> Thanks a lot.

Hello, dalao. Can I borrow your script of exporting the onnx file?

**Comment by notnitsuj** [comment]
@Stoooner My exporting script is just the same as any normal one. The difference is my modifications to some operations inside the model to fix incompatibility issues, but I don't really remember correctly all the things I have done. You can send me an email at work.ngmphuong@gmail.com with the specific problems you encounter and I'll show you a workaround.

P/s: I'm the one who emailed you asking for help with exporting Stark to TensorRT ;)
