### ISSUE TITLE
When test on got10k test, it raises error

### ISSUE THREAD

**Issue by laisimiao** [botaoye/OSTrack#13]
The error is:
`slice indices must be integers or None or have an __index__ method`
I don't know where it comes from (no hint to locate)

**Comment by botaoye** [comment]
You can set `--threads 0 --num_gpus 1 --debug 0` when testing, so that hints will be printed.

**Comment by laisimiao** [comment]
It happens in line 57 of processing_utils.py. 
```
File "tracking/../lib/train/data/processing_utils.py", line 57, in sample_target
    im_crop = im[y1 + y1_pad:y2 - y2_pad, x1 + x1_pad:x2 - x2_pad, :]
TypeError: slice indices must be integers or None or have an __index__ method
```
FIX:
add `target_bb = list(map(int, target_bb))` in line 28 of processing_utils.py.
