### ISSUE TITLE
How to set path?

### ISSUE THREAD

**Issue by 20XYSong** [botaoye/OSTrack#16]
大佬，问一个愚蠢的问题，怎么设置\lib\test\evaluation\local.py的路径啊？我先运行create_default_local_file.py设置好了各项路径，又在\lib\test\evaluation\local.py中设好各项路径，然后运行video_demo.py依然报错： YOU HAVE NOT SETUP YOUR local.py!!!
 Go to "F:\Pycharm Proj/project/project/CVlearning/OSTrack/tracking\..\lib\test\evaluation\local.py" and set all the paths you need. Then try to run again.

**Comment by botaoye** [comment]
The information provided is not sufficient. Try debugging to see if `local.py` is successfully loaded in the `env_settings()` function.

**Comment by 20XYSong** [comment]
It's not loaded successfully, error being 'No module named 'test.evaluation'; 'test' is not a package' when running at following step:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/82217292/177609260-98578fc5-b1d7-4146-ae14-a788fb724397.png">

**Comment by botaoye** [comment]
Make sure you are running on the correct root path and that `/lib\test\evaluation\local.py` exists. This may be caused by an incorrect path or a Windows path issue. Since I can't reproduce this error, I can't provide further guidance.

**Comment by 20XYSong** [comment]
Thanks for your advice. I will try to debug this problem. Thank you so much.
