### ISSUE TITLE
About the trigger condition of function candidate_elimination()

### ISSUE THREAD

**Issue by Soarkey** [botaoye/OSTrack#17]
Hi, Thanks for your excellent work!

When I was debugging the code of experiment `vitb_256_mae_ce_32x4_got10k_ep100`, I found that the `candidate_elimination()` function does not seem to be running, which seems to be different from the description in the paper. What is the reason for this, and what are the conditions under which the `candidate_elimination()` function will run?

**Comment by botaoye** [comment]
Thank you for your interest. The candidate elimination module is inserted into the `4, 7, 10' layers of the ViT model and `candidate_elimination()' will run on those layers, you are probably running the other layers at debugging time.

**Comment by Soarkey** [comment]
Is it related to `keep_ratio_search` always being 1.0 ?

![image](https://user-images.githubusercontent.com/17349395/177941676-fc3dbf1a-f4d0-492e-b8be-6028006390de.png)

code:
https://github.com/botaoye/OSTrack/blob/75823f40dc4761a104231944d8e312700131bcca/lib/models/layers/attn_blocks.py#L98

**Comment by botaoye** [comment]
Yes, there is a warm-up process for the candidate elimination module during training. Simply set `CE_START_EPOCH` and `CE_WARM_EPOCH` to 0 when debugging (the performance is still similar when these two are set to 0).

https://github.com/botaoye/OSTrack/blob/75823f40dc4761a104231944d8e312700131bcca/experiments/ostrack/vitb_256_mae_ce_32x4_got10k_ep100.yaml#L50-L51

**Comment by Soarkey** [comment]
It worked, thank you!
