### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by laisimiao** [botaoye/OSTrack#2]
Hi, nice work. Could you provide your total training time of 18*10^6 samples in 4 A100 as reference?

**Comment by botaoye** [comment]
Hi, thanks for your interest. Our OSTrack is friendly in terms of training time thanks to 1) fewer training image pairs; 2) consistency between training and testing (Siamese tracker requires feeding both the template and search region to the backbone for each training pair, which requires more time than testing).
The training time for OSTrack-256 and OSTrack-384 (without the early candidate elimination module) requires ~22h and ~29h for training  18*10^6 samples on 4*A100. (Note that our GPU server only has HDD, the training speed will boost if equipped with SSD).
In fact, OSTrack-256 (with the early candidate elimination module) can also be trained on 4*2080Ti (equipped with SSD) within ~23h.

**Comment by laisimiao** [comment]
Thanks, nice GPU-friend work, look forward to opening codes ASAP!
