### ISSUE TITLE
Could you please upload the training log?

### ISSUE THREAD

**Issue by Becomebright** [botaoye/OSTrack#21]
Hi! As reproducing the results for OSTrack-256, I got almost the same performance on other datasets except for LaSOT (68.0 AUC,  compared to 69.1 AUC in the paper). So I would like to compare my training logs with yours. Could you upload them?

**Comment by lawpdas** [comment]
Same problem. I trained OSTrack-256 with 2x3090 and batch size 64/GPU. I also got 68.62 LaSOT-AUC, which is slightly lower than 69.1 AUC.

**Comment by botaoye** [comment]
Sorry to hear that, the training log is available at [vitb_256_mae_ce_32x4_ep300.log](https://drive.google.com/file/d/1Z7J4E2GEldlPMeefD4J52Rxb3mVflh7Y/view?usp=sharing). Since I re-implemented the project before making it public, I did not re-train the models again. And I will try to train OSTrack-256 again to see the performance then. By the way, you two also provide a different LaSOT performance, which is strange.

**Comment by Becomebright** [comment]
My final IoU (~0.86) is lower than yours (~0.87). I will train the model for some additional epochs to see if it can converge to that state. 
BTW, I trained on 4x A100 with PyTorch 1.9.0 and CUDA 11.1. Did you train this model on A100 or 2080Ti?

**Comment by botaoye** [comment]
I trained on 4x A100. I use pytorch1.8 before, but pytorch1.8 is not suitable for A100, which will cause a much longer training time. Currently, I use PyTorch 1.10.0 and CUDA 11.3, maybe you can try this env setting.

**Comment by Becomebright** [comment]
Thanks a lot. I will give it a try.

**Comment by Becomebright** [comment]
I trained OSTrack-256 with PyTorch 1.10.0 and CUDA 11.3. The final IoU is still around 0.866, lower than your 0.871.

Benchmark results:
Paper: LaSOT 69.1, UAV123 68.3, NFS 64.7, TNL2K 54.3
Mine: LaSOT 68.2, UAV123 67.5, NFS 64.4, TNL2K 55.1

Did you train it again?

**Comment by botaoye** [comment]
> I trained OSTrack-256 with PyTorch 1.10.0 and CUDA 11.3. The final IoU is still around 0.866, lower than your 0.871.
> 
> Benchmark results: Paper: LaSOT 69.1, UAV123 68.3, NFS 64.7, TNL2K 54.3 Mine: LaSOT 68.2, UAV123 67.5, NFS 64.4, TNL2K 55.1
> 
> Did you train it again?

Hi, I re-train the model, and the final LaSOT AUC is 69.2, almost the same as the paper.

**Comment by Becomebright** [comment]
Thanks a lot for your help. I will try it later.
