### ISSUE TITLE
Details of OSTrack's implementation on the TNL2K dataset

### ISSUE THREAD

**Issue by Soarkey** [botaoye/OSTrack#22]
Thank you for your excellent work!
I noticed in the result report of the paper that the accuracy of the `TNL2K` dataset is 54.3, would you please tell me how `OSTrack` incorporates the natural language information for tracking? I sincerely hope you could explain my doubts.

**Comment by botaoye** [comment]
Hi, when testing on the TNL2k dataset, we only use the RGB image, and the natural language information is not used.
