### ISSUE TITLE
Could you please upload the trained OSTrack model using the ImageNet-1k and ImageNet-21k pre-training methods？

### ISSUE THREAD

**Issue by WeGoHard** [botaoye/OSTrack#25]
Hi! As reproducing the ablation study results for OSTrack-256, I had encountered difficulties to get the same performance using the ImageNet-1k and ImageNet-21k pre-training methods. So I would like to compare the models with yours. Could you upload them?

**Comment by botaoye** [comment]
Hi, as mentioned in the paper, the reported IN1k and IN21k results are acquired from the models without the early candidate elimination module. You can directly use this [config file](https://drive.google.com/file/d/1M5ik5Lj-UlMzsufqZ-ZeoOlSz1xXzxqi/view?usp=sharing) to train an IN1k pre-trained model.
