### ISSUE TITLE
How to save a checkpoint after each epoch in the training process?

### ISSUE THREAD

**Issue by userlooser1** [botaoye/OSTrack#26]
How to save a checkpoint after each epoch in the training process?

**Comment by botaoye** [comment]
Hi, to save a checkpoint after each epoch, you can change the following line:

 https://github.com/botaoye/OSTrack/blob/f616967ab8074b11b1efa9f4486e9d6b19f25a7a/lib/train/trainers/base_trainer.py#L95

to:
```
 if epoch > (max_epochs - 1) or save_every_epoch or epoch % 1== 0 or epoch in save_epochs or epoch > (max_epochs - 5): 
```
