### ISSUE TITLE
Tracking when object is out of frame

### ISSUE THREAD

**Issue by morkovka1337** [botaoye/OSTrack#27]
Hi! Thanks for the great model, when I first run it I was pretty much impressed by the quality \ FPS trade-off.

However, in my scenario, object is not always in the frame (i.e. it can disappear and appear again after several seconds \ minutes). I've slightly modified the code so that `tracker.track` returns also a classification score, but this does not help much. When the object is out of frame, tracker can stick to the wrong object with high enough confidence. 
I'm considering now implementing a classification head (that will classify is search object is present on the template) with corresponding changes in the training procedure and would like to know other thoughts how to deal with such scenario.

Thanks!

**Comment by botaoye** [comment]
This is a typical long-term tracking problem. You can add a classification head or refer to some previous long-term tracking methods (see VOT challenge report for more details).
