### ISSUE TITLE
How to choose a checkpoint for testing the model using it?

### ISSUE THREAD

**Issue by userlooser1** [botaoye/OSTrack#28]
How to choose a checkpoint for testing the model using it?

And how to use model in inference mode with pretrained weights?

**Comment by botaoye** [comment]
We use the latest model for testing. If you want to use the intermediate saved checkpoints, just change the following line:
https://github.com/botaoye/OSTrack/blob/f616967ab8074b11b1efa9f4486e9d6b19f25a7a/experiments/ostrack/vitb_256_mae_ce_32x4_ep300.yaml#L82
