### ISSUE TITLE
Inference OSTrack model with onnxruntime(C++) and TensorRT(C++)

### ISSUE THREAD

**Issue by Stoooner** [botaoye/OSTrack#29]
I have exported the OSTrack model to an onnx file and used onnxruntime(C++) and TensorRT(C++) for inference，the details are as follows:
------------------------------------
Testing platform 1: Desktop-PC
model: vitb_256_mae_ce_32x4_ep300
GPU: RTX 2060(8G)
cuda_version: 11.5
cudnn_version: 8.3
opencv_version: 4.5.4
gcc_version: 7.5.0
onnxruntime_version: onnxruntime-linux-x64-gpu-1.6.0;
TensorRT_version: 8.4.5.1
FPS:
- onnxruntime(C++): ~ 70 FPS
- TensorRT(C++, FP32): ~92 FPS
- TensorRT(C++, FP16): ~240 FPS
- **NewResult:** 
>- TensorRT(C++ + FP16 + cv::cuda): ~270 FPS(2022.09.05)
>- TensorRT(C++ + FP16 + cv::cuda. Comment out cv::imshow and cv::putText, just include preprocess + infer + postprocess): ~284FPS(2022.09.06)
------------------------------------
Now, I have tested the model on Jetson Agx NX, here is the results:
Testing platform 2: Nvidia jetson agx NX
model: vitb_256_mae_ce_32x4_ep300
jetpack_version: 5.0.2
cuda_version: 11.4
cudnn_version: 8.4
opencv_version: 4.5.4
gcc_version: 7.5.0
onnxruntime_version: onnxruntime-linux-aarch64-gpu-1.6.0;
TensorRT_version: 8.4.1.5
FPS:
- onnxruntime(C++): ~25 FPS (**<u>This result is tested on Nvidia Jetson Agx Xavier(16 G)</u>**)
- TensorRT(C++, FP16): ~45 FPS(**<u>This result is tested on Nvidia Jetson Agx NX</u>**)
- **NewResult:**
- TensorRT(C++ + FP16 + cv::cuda. Comment out cv::imshow and cv::putText, just include preprocess + infer + postprocess): ~49FPS(2022.09.06)
![OSTrack_1](https://user-images.githubusercontent.com/31228436/187054775-a3f2896a-e37d-4327-ae9e-f434bf12df7b.png)
![OSTrack_2](https://user-images.githubusercontent.com/31228436/187054778-bff27d6e-1352-4ca9-8386-b124f0df645e.png)
![OSTrack_3](https://user-images.githubusercontent.com/31228436/187054779-fb0760df-d15c-46da-bf37-5ee955ae129f.jpg)
**(2022.09.05)=================================================================**
![ostrack2](https://user-images.githubusercontent.com/31228436/188310071-826a3feb-e6f7-4bc0-affa-0f6d2a4b4727.png)
![ostrack4](https://user-images.githubusercontent.com/31228436/188448855-7a2f26ae-5b69-449c-a150-83207cc2b097.png)

--------------------------------------
**Attention** :
- The Opencv name window is still stark, and I have forgot to modify the window name, the model is OSTrack;
- The fan of jetpack 5.0.2 is **DISABLED**, maybe it's a bug of  jetpack 5.0.2. And i have confirmed this situation with @notnitsuj, he said this situation is also appeared on jetpack5.0.1. So maybe this is a bug of jetpack 5.0.2, and maybe inference speed will be more powerful when the fan is maxed out. so thank you @notnitsuj again.
--------------------------------------
Finally, I would like to thanks @notnitsuj for some help, thank you so much.

**Comment by zanilzanzan** [comment]
Hey @Stoooner, first of all, congrats! :D The improved runtimes look pretty good. Do you possibly have the converted models or conversion scripts available somewhere?

**Comment by Stoooner** [comment]
> Hey @Stoooner, first of all, congrats! :D The improved runtimes look pretty good. Do you possibly have the converted models or conversion scripts available somewhere?

Hi, my script of exporting the onnx file is modified by referring to the exporting script of Stark tracker model, you can directly refer to the script of the stark model to modify and use. However, it should be noted that some pytorch code in the OSTrack model need to be replaced and modified, otherwise some calculation operators of onnx file that cannot be inferenced on the inference framework(like onnxruntime or TensorRT) will be generated.

**Comment by Stoooner** [comment]
> Hey @Stoooner, first of all, congrats! :D The improved runtimes look pretty good. Do you possibly have the converted models or conversion scripts available somewhere?

Hi, my script of exporting the onnx file is modified by referring to the exporting script of Stark tracker model, you can directly refer to the script of the stark model to modify and use. However, it should be noted that some pytorch code in the OSTrack model need to be replaced and modified, otherwise some calculation operators of onnx file that cannot be inferenced on the inference framework(like onnxruntime or TensorRT) will be generated.

**Comment by 1qingfeng-1** [comment]
First of all congratulations, great work, can you provide a detailed script for onnx transfer? Thanks!

**Comment by Stoooner** [comment]
> First of all congratulations, great work, can you provide a detailed script for onnx transfer? Thanks!

原始python代码中有很多细节我进行了更改，这边即便给你onnx导出脚本，你也应该是没法使用的，你可以直接参照stark模型的onnx导出脚本进行更改，如果还是想询问细节的话可以给我发邮件，我的邮箱是2582814014@qq.com.

**Comment by 1qingfeng-1** [comment]
> > 首先恭喜，辛苦了，能不能提供详细的onnx传输脚本？谢谢！
> 
> 原始python代码里面有很多我进行了更改的模型，这个主题给你onnx的内容，你也应该是使用的，你可以直接如果stark的onnx导出的细节进行细节更改，还是想了解的话可以给我发邮件，我的邮箱是[2582814014@qq.com](mailto:2582814014@qq.com)。
hi, thank you for your suggestion, I have successfully exported the onnx model, it can run 8~9fps in cpu mode, I will use ncnn for acceleration later, and I will provide a performance test report after my verification is completed.

**Comment by Stoooner** [comment]
> > > 首先恭喜，辛苦了，能不能提供详细的onnx传输脚本？谢谢！
> > 
> > 
> > 原始python代码里面有很多我进行了更改的模型，这个主题给你onnx的内容，你也应该是使用的，你可以直接如果stark的onnx导出的细节进行细节更改，还是想了解的话可以给我发邮件，我的邮箱是[2582814014@qq.com](mailto:2582814014@qq.com)。
> 
> * hi, thank you for your suggestion, I have successfully exported the onnx model, it can run 8~9fps in cpu mode, I will use ncnn for acceleration later, and I will provide a performance test report after my verification is completed.

恭喜你成功导出了onnx文件，请问你是在什么配置的平台上跑8~9 FPS的呢？

**Comment by xingxinghanzi** [comment]
> > > 首先恭喜，辛苦了，能不能提供详细的onnx传输脚本？谢谢！
> > 
> > 
> > 原始python代码里面有很多我进行了更改的模型，这个主题给你onnx的内容，你也应该是使用的，你可以直接如果stark的onnx导出的细节进行细节更改，还是想了解的话可以给我发邮件，我的邮箱是[2582814014@qq.com](mailto:2582814014@qq.com)。
> 
> * hi, thank you for your suggestion, I have successfully exported the onnx model, it can run 8~9fps in cpu mode, I will use ncnn for acceleration later, and I will provide a performance test report after my verification is completed.

hi, have you completed the acceleration by ncnn? I am trying accelerate the model by MNN and ncnn, but failured

**Comment by Ru6887** [comment]
> > Hey @Stoooner, first of all, congrats! :D The improved runtimes look pretty good. Do you possibly have the converted models or conversion scripts available somewhere?
> 
> Hi @zanilzanzan, my script of exporting the onnx file is modified by referring to the exporting script of Stark tracker model, you can directly refer to the script of the stark model to modify and use. However, it should be noted that some pytorch code in the OSTrack model need to be replaced and modified, otherwise some calculation operators of onnx file that cannot be inferenced on the inference framework(like onnxruntime or TensorRT) will be generated.

can you send the modified pytrorch code?
