### ISSUE TITLE
vis可视化问题

### ISSUE THREAD

**Issue by chenhui2016** [botaoye/OSTrack#31]
我按照readme文件给出的步骤（可视化部分）， 结果test文件都运行结束了 8097端口号依旧全是蓝屏。
随后我又在网上随便找了测试visdom的代码，别人的代码可以正常显示，所以visdom是没有错误的。
请问这个应该怎么解决？

**Comment by botaoye** [comment]
我测试过可视化是没有问题的，如果你始终无法解决的话，也许需要提供更多的信息
