### ISSUE TITLE
Train on RTX3090 with CUDA11.2

### ISSUE THREAD

**Issue by hmbb123** [botaoye/OSTrack#32]
I have 4*RTX3090 with CUDA11.2, You only gave the configuration of cuda11.3. How can I configure with cuda11.2? 
I train according to the environment I used before (Python 3.8.10, Python 1.9.0, cudatoolkit 11.1.74). The batchsize is set to 32, and the time for training one epoch is about 16 minutes. Is this correct?

**Comment by botaoye** [comment]
- You can use cuda11.2 by configuring the environment by yourself. 
- 16 minutes is way too long. You may check your IO and CPU performance.

**Comment by wjh-scut** [comment]
> I have 4*RTX3090 with CUDA11.2, You only gave the configuration of cuda11.3. How can I configure with cuda11.2? I train according to the environment I used before (Python 3.8.10, Python 1.9.0, cudatoolkit 11.1.74). The batchsize is set to 32, and the time for training one epoch is about 16 minutes. Is this correct?

Hi, I have a similar problem. Have you solved it?
