### ISSUE TITLE
关于LTRLoader中的collate_fn和stack_dim的问题

### ISSUE THREAD

**Issue by l-sf** [botaoye/OSTrack#36]
请问lib/train/data/loader.py中的class LTRLoader为何要传入collate_fn函数，以及stack_dim=1，在上面实现的ltr_collate_stack1函数和默认的只有torch.stack()中的dim不一样，但是我测试dim=0和dim=1效果一样，可不可以不传入collate_fn函数呢？直接用torch.utils.data.dataloader.DataLoader中默认的呢？

**Comment by botaoye** [comment]
LTRLoader是因为代码支持多个template或者search region，因此多了一个维度。你可以修改使用默认的collate_fn，但是注意一下actor中保持维度一致就行。

**Comment by l-sf** [comment]
感谢您的回复！
