### ISSUE TITLE
about keep ratio?

### ISSUE THREAD

**Issue by jasonwuyiwei** [botaoye/OSTrack#38]

**Comment by jasonwuyiwei** [comment]
why the keep ratio is 0.7 0.7 0.7 .is there any experiment on anther like  0.9 0.8 0.7 or 0.7,0.8 ,0.9 ?

**Comment by botaoye** [comment]
Hi, we have reported the performance under different keep ratios in the appendix, you can also try more settings if you want.

**Comment by jasonwuyiwei** [comment]
> Hi, we have reported the performance under different keep ratios in the appendix, you can also try more settings if you want.

thank you very much
