### ISSUE TITLE
您好，作者。请问您论文中的热力图是如何制作的，有没有开源代码。

### ISSUE THREAD

**Issue by Quan-w** [botaoye/OSTrack#39]

**Comment by botaoye** [comment]
目前代码中没有这部分。图是通过template中心的token对所有search region token的attention weight，我会在后续更新这部分代码。

**Comment by RelayZ** [comment]
你好，请问这部分代码准备公布了吗？最近想对比一下您的可视化结果，但是不知道如何对shape为(8, 12, 256, 64).的attention weight进行可视化。

**Comment by RelayZ** [comment]
> 

已解决。

**Comment by RelayZ** [comment]
> 你好，请问这部分代码准备公布了吗？最近想对比一下您的可视化结果，但是不知道如何对shape为(8, 12, 256, 64).的attention weight进行可视化。

已解决。
