### ISSUE TITLE
Approximate code release date

### ISSUE THREAD

**Issue by zanilzanzan** [botaoye/OSTrack#4]
Dear authors, do you have any planned date for releasing the code? Thanks in advance!

**Comment by botaoye** [comment]
Hi, thanks for your interest. Since I am currently very busy, I will start cleaning up the code in the next few weeks depending on how much time will I have in the upcoming weeks. However, I believe the code will be available within a month.

**Comment by zanilzanzan** [comment]
Thanks for the reply! Looking forward to it!
