### ISSUE TITLE
关于TNL2K测试问题

### ISSUE THREAD

**Issue by chenxin-dlut** [botaoye/OSTrack#45]
作者您好，请问这份代码可以直接用来test和eval TNL2K数据集吗？

**Comment by botaoye** [comment]
您好，可以的。已经提供TNL2K的数据集 https://github.com/botaoye/OSTrack/blob/main/lib/test/evaluation/tnl2kdataset.py 不过路径和其他一下内容还需要自己添加以下，等过段时间空点我会尽快更新的。
