### ISSUE TITLE
按照要求下的，但是提示有个参数和model不匹配。checkpoint不对

### ISSUE THREAD

**Issue by zhaoxingle** [botaoye/OSTrack#47]
Error(s) in loading state_dict for OSTrack:
        size mismatch for backbone.pos_embed_z: copying a param with shape torch.Size([1, 64, 768]) from checkpoint, the shape in current model is torch.Size([1, 144, 768]).

**Comment by botaoye** [comment]
It seems that your downloaded model and the config file do not match.
