### ISSUE TITLE
Candidate Elimination start epoch

### ISSUE THREAD

**Issue by Roger-Liang** [botaoye/OSTrack#49]
Thank you for you great work! I have a question about CE module.
Did you do some ablation experiments about the CE_START_EPOCH and CE_WARM_EPOCH?
How did you choose these parameters?

**Comment by botaoye** [comment]
We just chose these two parameters intuitively. We did try a few different numbers and got similar performance, indicating that this module is not sensitive to these two parameters.

**Comment by Roger-Liang** [comment]
> We just chose these two parameters intuitively. We did try a few different numbers and got similar performance, indicating that this module is not sensitive to these two parameters.
thank you for your reply! I get it.
