### ISSUE TITLE
是GOTleader board上的吗？

### ISSUE THREAD

**Issue by llz-lian** [botaoye/OSTrack#5]
为什么hz这么低

**Comment by botaoye** [comment]
We adopt multi-process and multi-GPU and multi-process testing to accelerate the testing process, thus reducing the speed of a single sequence. Currently, you can refer to [Stark](https://github.com/researchmm/Stark#test-and-evaluate-stark-on-benchmarks) for more details.

**Comment by llz-lian** [comment]
有单线程的数据吗？

**Comment by botaoye** [comment]
> 有单线程的数据吗？

Sorry for the late reply. I will update the speed of the single thread soon. Our code will also be available soon. the tracker on the GOT-10k leaderboard is different from the original OSTrack and may be available later.
