### ISSUE TITLE
关于测试和可视化问题

### ISSUE THREAD

**Issue by UnlimitedWand** [botaoye/OSTrack#50]
您好，在单独测试速度时fps很快，但是在evaluation和可视化时，fps只有十几，请问怎么设置可以让速度变快？谢谢！

**Comment by botaoye** [comment]
由于在evaluation的时候，会有额外的图像读取和处理，您的速度这么慢也许是由于cpu或者io的问题。可视化时网络传输可能也会对速度造成影响。

**Comment by UnlimitedWand** [comment]
好的，谢谢，我再排查一下问题
