### ISSUE TITLE
关于不加CE( Candidate Elimination)如何进行速度测试

### ISSUE THREAD

**Issue by USCT-YQJ** [botaoye/OSTrack#53]
你好，请问不加CE如何进行模型速度测试？

**Comment by botaoye** [comment]
在测试速度时，把config换成 [vitb_256_mae_32x4_ep300.yaml](https://github.com/botaoye/OSTrack/blob/main/experiments/ostrack/vitb_256_mae_32x4_ep300.yaml) 就可以了
