### ISSUE TITLE
Training on LaSOT

### ISSUE THREAD

**Issue by xiajianqiang** [botaoye/OSTrack#54]
您好，在阅读您的代码时，发现您通过vitb_256_mae_ce_32x4_ep300.yaml配置文件，在lib/train/base_functions.py中的names2datasets函数中加载了lasot,got10k,coco17,trackingnet四个数据集的训练集数据进行训练。想问一下您，如果想只复现您在论文中所展示的lasot数据集上的结果，是不是在这里只要加载lasot的训练集就可以了，还是也需要加载上述所有数据集的训练集。

**Comment by botaoye** [comment]
不是的，论文中lasot数据集上的结果是在全部四个数据集上训练得到的

**Comment by xiajianqiang** [comment]
非常感谢您的回答，我也是刚接触视觉目标跟踪这个方向，恰巧您的文章是我复现的第一篇paper，想问一下您，在深度学习视觉目标跟踪领域中，是可以使用额外的训练集来对模型进行训练，然后在当前数据集的测试集上进行测试的吗？这样的话，是不是在与baseline的对比中，只需要保证对比模型具有相同的训练集和训练方式就可以。

**Comment by botaoye** [comment]
是的，只有GOT10k test set是要求只在GOT10k train set上就行训练的。

**Comment by xiajianqiang** [comment]
非常感谢，很棒的工作，后续会基于您的模型做一些相关的工作。
