### ISSUE TITLE
关于Early Candidate Elimination的问题

### ISSUE THREAD

**Issue by hernandez-hkp** [botaoye/OSTrack#55]
作者你好，请问假设现在有目标面积，可以使用你在文章中提到的 **Early Candidate Elimination** 直接删除全部背景区域，从而得到最终的结果吗？我们尝试了一下，得到的效果很差，具体表现在剩下的**Patch**很分散，不确定是否是操作问题。希望得到你的回答！

**Comment by botaoye** [comment]
如果keeping ratio很小，模型性能肯定会下降，无法准确识别出完整的bbox区域。此外，训练和测试时keeping ratio不一致可能也会对性能有影响。

**Comment by hernandez-hkp** [comment]
谢谢你的解答！
