### ISSUE TITLE
模型性能问题

### ISSUE THREAD

**Issue by Azong-HQU** [botaoye/OSTrack#56]
作者您好，最近正在拜读您杰出的工作，但当我在跑您的代码时发现了一个关于性能的问题: 我没改任何代码和配置文件，根据您的配置进行训练，但训出来的模型性能没法达到您论文中的效果，总会低2个点左右。比如384尺寸的OSTrack: paper中lasot AO是71.1，我跑出来的模型只能到69.5左右。请问作者这会是什么问题导致的呢？

希望您有时间时能回复一下我，谢谢！！！

**Comment by MonsterZUO** [comment]
> 

同学,想问一下,你训练是从头重新训练的是么?  你有尝试过继续作者的训练吗?
我在尝试load作者给的model zoo中的checkpoint, 然后继续训练, 发现checkpoint文件是不完整的,不能继续训练

**Comment by botaoye** [comment]
> 

我没有遇到过这种情况，正常情况下会有波动但不会差距这么大。你的其他数据集上的测试结果是多少呢？

**Comment by botaoye** [comment]
> > 
> 
> 同学,想问一下,你训练是从头重新训练的是么? 你有尝试过继续作者的训练吗? 我在尝试load作者给的model zoo中的checkpoint, 然后继续训练, 发现checkpoint文件是不完整的,不能继续训练

为了缩小模型体积，checkpoint里面关于优化的一些参数没有保存。如果你想在这个参数基础上直接训练，需要把参数load到新的模型上训练，而不是从300 epoch后继续训练

**Comment by LY-1** [comment]
作者您好，请问训练出来的权重怎么选择最好的一个呢？

**Comment by botaoye** [comment]
> 作者您好，请问训练出来的权重怎么选择最好的一个呢？

可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。

**Comment by LY-1** [comment]
> > 作者您好，请问训练出来的权重怎么选择最好的一个呢？
> 
> 可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。

我现在是用的`vitb_384_mae_ce_32x4_ep300`，在got-10k上面训练的，因为GPU显存的问题，我将训练的batch_size调整为16，并且用了预训练模型。测试的时候选择的是最后一个权重（OSTrack_ep0100.pth.tar），但我测出来的性能和论文中`vitb_256_mae_ce_32x4_ep300`差不多，方便告知是啥原因嘛？

**Comment by botaoye** [comment]
> > > 作者您好，请问训练出来的权重怎么选择最好的一个呢？
> > 
> > 
> > 可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。
> 
> 我现在是用的`vitb_384_mae_ce_32x4_ep300`，在got-10k上面训练的，因为GPU显存的问题，我将训练的batch_size调整为16，并且用了预训练模型。测试的时候选择的是最后一个权重（OSTrack_ep0100.pth.tar），但我测出来的性能和论文中`vitb_256_mae_ce_32x4_ep300`差不多，方便告知是啥原因嘛？

修改batch size请对应调整learning rate

**Comment by LY-1** [comment]
> > > > 作者您好，请问训练出来的权重怎么选择最好的一个呢？
> > > 
> > > 
> > > 可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。
> > 
> > 
> > 我现在是用的`vitb_384_mae_ce_32x4_ep300`，在got-10k上面训练的，因为GPU显存的问题，我将训练的batch_size调整为16，并且用了预训练模型。测试的时候选择的是最后一个权重（OSTrack_ep0100.pth.tar），但我测出来的性能和论文中`vitb_256_mae_ce_32x4_ep300`差不多，方便告知是啥原因嘛？
> 
> 修改batch size请对应调整learning rate

好的，我改为了原有batch size的1/2，学习率也是原有学习率的1/2嘛？另外还需要调整其它的超参吗？

**Comment by botaoye** [comment]
> > > > > 作者您好，请问训练出来的权重怎么选择最好的一个呢？
> > > > 
> > > > 
> > > > 可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。
> > > 
> > > 
> > > 我现在是用的`vitb_384_mae_ce_32x4_ep300`，在got-10k上面训练的，因为GPU显存的问题，我将训练的batch_size调整为16，并且用了预训练模型。测试的时候选择的是最后一个权重（OSTrack_ep0100.pth.tar），但我测出来的性能和论文中`vitb_256_mae_ce_32x4_ep300`差不多，方便告知是啥原因嘛？
> > 
> > 
> > 修改batch size请对应调整learning rate
> 
> 好的，我改为了原有batch size的1/2，学习率也是原有学习率的1/2嘛？另外还需要调整其它的超参吗？

其他不需要改，如果你也是4卡，那就试试lr改为原来的1/2

**Comment by botaoye** [comment]
> > > > > > > 作者您好，请问训练出来的权重怎么选择最好的一个呢？
> > > > > > 
> > > > > > 
> > > > > > 可以可以根据自己的需要选择，`vitb_384_mae_ce_32x4_ep300`的性能较高，速度慢一些。相反`vitb_256_mae_ce_32x4_ep300`的性能稍微低点，但是速度快一些。
> > > > > 
> > > > > 
> > > > > 我现在是用的`vitb_384_mae_ce_32x4_ep300`，在got-10k上面训练的，因为GPU显存的问题，我将训练的batch_size调整为16，并且用了预训练模型。测试的时候选择的是最后一个权重（OSTrack_ep0100.pth.tar），但我测出来的性能和论文中`vitb_256_mae_ce_32x4_ep300`差不多，方便告知是啥原因嘛？
> > > > 
> > > > 
> > > > 修改batch size请对应调整learning rate
> > > 
> > > 
> > > 好的，我改为了原有batch size的1/2，学习率也是原有学习率的1/2嘛？另外还需要调整其它的超参吗？
> > 
> > 
> > 其他不需要改，如果你也是4卡，那就试试lr改为原来的1/2
> 
> 我是单张卡。

那就是1/8

**Comment by LY-1** [comment]
非常感谢，问题已解决

**Comment by Leonhard-Euler-ai** [comment]
请问单机多卡训练代码实现上是模型并行的吗

**Comment by jeannotes** [comment]
@LY-1 你单张卡训练要多久

**Comment by LY-1** [comment]
> @LY-1 你单张卡训练要多久

2-3天
