### ISSUE TITLE
可视化问题

### ISSUE THREAD

**Issue by Nightwatch-Fox11** [botaoye/OSTrack#58]
您好，请问该如何得到您代码中的`attention weight`热力图呢，是否有相关代码可以参考，并且我想知道在进行`candidate eliminate`之后的`attention weight`已经发生了`shape`的改变，您是将`attention weight`进行补全后可视化么？

**Comment by botaoye** [comment]
你好，
1. 如果是添加了candidate eliminate，那么需要进行补全后可视化，在我们论文中的Fig.4是没有添加candidate eliminate的可视化
2. 你可以参考DETR的可视化代码

**Comment by Nightwatch-Fox11** [comment]
好的，十分感谢您的回复
