### ISSUE TITLE
Could you provide a guideline or tips on how to change the backbone of the tracker to e.g., ResNet50 

### ISSUE THREAD

**Issue by HamDan1999** [botaoye/OSTrack#59]
Could you provide a guideline or tips on how to change the backbone of the tracker to e.g., ResNet50?

**Comment by botaoye** [comment]
ResNet50 is not applicable to our approach because we need attention layers for joint feature learning and relationship modeling. However, you can use other variants of the visual transformer model (e.g., CaiT, CvT).
