### ISSUE TITLE
Could you tell me if you using any data augmentation?

### ISSUE THREAD

**Issue by AlexDotHam** [botaoye/OSTrack#6]
Could you tell me if you using any data augmentation?

**Comment by AlexDotHam** [comment]
And also could you tell me how large the IOU LOSS at the end of the training is ?

**Comment by botaoye** [comment]
Hi, 1) we follow the common practice of previous transformer trackers (e.g., TransT, STARK) to use horizontal flip and brightness jittering for training.  2) For OSTrack-256, the final `IoULoss` is within 0.13-0.14.

We plan to release our code recently, and the training logs will also be provided.

**Comment by AlexDotHam** [comment]
don't you using any scale jitter or center jitter?

**Comment by Dellary** [comment]
We are looking forward to seeing you release the code as soon as possible. We are very interested and have been watching!

**Comment by botaoye** [comment]
> We are looking forward to seeing you release the code as soon as possible. We are very interested and have been watching!

Thank you for your interest, the code will be available in 1 or 2 days.
