### ISSUE TITLE
train on dataset

### ISSUE THREAD

**Issue by guetaro** [botaoye/OSTrack#61]
Hi,

In the train script there is no option to control which dataset to train on (in the test phase there is the variable --dataset). How can I control which dataset to use when train.

Thank you

**Comment by botaoye** [comment]
You can change the training dataset in the config file. For example, you can change the following lines. https://github.com/botaoye/OSTrack/blob/eff2d630af740c5cae92ef00f09964cea9a23da0/experiments/ostrack/vitb_256_mae_ce_32x4_ep300.yaml#L29-L39

**Comment by botaoye** [comment]
Sorry, I can't find the problem with the limited information I have.
