### ISSUE TITLE
vot2019的实验结果较低

### ISSUE THREAD

**Issue by kongbia** [botaoye/OSTrack#62]
我用公布的模型在vot19上测试EAO很低，只有0.284，而在其他数据集上的测得的结果和论文中类似，请问ostrack为何在vot19上的效果不佳

**Comment by botaoye** [comment]
我们没在vot19测试过，所以不确定问题所在。但是在VOT20测试过，即使再不适用template updating的策略下，我们的方法也能取得比较好的效果。（VOT数据集由于distractor较多，所以template updating对结果影响非常大），结果见我们arXiv paper的附录。VOT19的指标已经过时了，现在大家一般不去测试。
