### ISSUE TITLE
平均注意力权重问题

### ISSUE THREAD

**Issue by Coronal-yup** [botaoye/OSTrack#63]
请问您候选区域消除里面平均注意力权重最大的点（也就是排序i=0的点）落在目标上的可能性与跟踪成功率差不多吗？我们打算在您的基础上完成一些工作，希望能尽快得到您的回答！

**Comment by botaoye** [comment]
我们没有就行相关实验，我们代码和模型完全公开，您可以自己就行实验。

**Comment by Coronal-yup** [comment]
好的。请问您公布热力图的代码了吗？

**Comment by Dinosaurcubs** [comment]
> 请问您候选区域消除里面平均注意力权重最大的点（也就是排序i=0的点）落在目标上的可能性与跟踪成功率差不多吗？我们打算在您的基础上完成一些工作，希望能尽快得到您的回答！

你好，麻烦问下注意力可视化成功了吗，可否指点下我
