### ISSUE TITLE
单卡训练问题

### ISSUE THREAD

**Issue by 7854221** [botaoye/OSTrack#64]
请问如果使用单卡训练的话除了要设置 --nproc per node 1 还需要什么操作吗

**Comment by 7854221** [comment]
出现问题ERROR:torch.distributed.elastic.multiprocessing.api:failed(exitcode:1) local_rank: 0 ,(pid: 10324) of binary:

**Comment by 7854221** [comment]
出现问题KeyError:'net'希望您有时间可以回复一下，谢谢

**Comment by botaoye** [comment]
You can train with a single GPU by setting `--mode single`:
`python tracking/train.py --script ostrack --config vitb_256_mae_ce_32x4_ep300 --save_dir ./output --mode single --use_wandb 1`

**Comment by 7854221** [comment]
谢谢您的解答，使用您的代码在got10k测试完后打包在got10k官网上为什么评估不出来结果呢

**Comment by botaoye** [comment]
按照readme操作后提交got10k_submit.zip文件

**Comment by 7854221** [comment]
> 按照readme操作后提交got10k_submit.zip文件

谢谢您的解答已经解决

**Comment by yepingapril** [comment]
> 出现问题KeyError:'net'希望您有时间可以回复一下，谢谢

请问解决了吗，我也遇到同样的问题
