### ISSUE TITLE
训练时长问题

### ISSUE THREAD

**Issue by xiajianqiang** [botaoye/OSTrack#65]
想问一下您在使用4个NVIDIA A100显卡进行训练时，训练大概多长时间呀？您的使用A100是40GB显存的型号还是80GB显存的型号？谢谢！

**Comment by botaoye** [comment]
训练时间小于1天，用的是40G显存版本。

**Comment by xiajianqiang** [comment]
嗯嗯，好的，这个训练时间是指在加载了预训练参数的情况下吗？

**Comment by xiajianqiang** [comment]
嗯嗯，好的，这个训练时间是指在加载了预训练参数的情况下吗？

**Comment by botaoye** [comment]
是的

**Comment by xiajianqiang** [comment]
非常感谢
