### ISSUE TITLE
使用不同的训练资料集

### ISSUE THREAD

**Issue by CooolWindS** [botaoye/OSTrack#66]
您好，
如果我需要使用自己的资料集来训练OSTrack，请问我只需要准备影像资料以及对应的groundtruth.txt吗? 举例格式如下
```
-- dataset
     -- 我的训练资料集
         |-- 类1
              |-- Image1.jpg
              |-- Image2.jpg
              ...
              |-- groundtruth.txt
         |-- 类2
         |-- 类3
         ...
```

有其他资料是需要准备的吗？
(以got10K为例，它每类资料夹内有包含absence.label、cover.label、cut_by_image.label以及meta_info.ini等其他四项资料)
谢谢！

**Comment by botaoye** [comment]
> 您好，请问以下按照 官网 配置好的环境，您的 numpy 的版本是多少，麻烦您看一下然后回复我一下吗，谢谢了

numpy版本没有太大影响，随意。或者你可以参考 [ostrack_cuda113_env.yaml](https://github.com/botaoye/OSTrack/blob/main/ostrack_cuda113_env.yaml) 中的版本。

**Comment by CooolWindS** [comment]
感谢回复！

**Comment by CooolWindS** [comment]
> > 
> 
> 是的，只需要图像和groundtruth.txt，其他不是必须，每帧目标是否缺失可以从groundtruth中推断。

您好，
以我的理解以及trace code之后，我想再确认，OSTrack的模型在追踪物体时，template是否都是固定不变，以一部影片作为输入，template是否都会一直是第一帧所标注的物体?

**Comment by botaoye** [comment]
> > > 
> > 
> > 
> > 是的，只需要图像和groundtruth.txt，其他不是必须，每帧目标是否缺失可以从groundtruth中推断。
> 
> 您好，再请问一问题 以我的理解以及trace code之后，我想再确认，OSTrack的模型在追踪物体时，template是否都是固定不变，以一部影片作为输入，template是否都会一直是第一帧所标注的物体?

是的

**Comment by AlanHuangKP** [comment]
@CooolWindS 您好，请问您自定义训练数据集的代码可以发我参考一下吗？非常感谢！

**Comment by Barryalana** [comment]
@CooolWindS 你好，想问下你训练自己的数据集成功了么，我用的数据集只添加groundtruth.txt无法运行提示找不到absence.label文件，请问你是如何解决的？

**Comment by jeannotes** [comment]
> > > > 
> > > 
> > > 
> > > 是的，只需要图像和groundtruth.txt，其他不是必须，每帧目标是否缺失可以从groundtruth中推断。
> > 
> > 
> > 您好，再请问一问题 以我的理解以及trace code之后，我想再确认，OSTrack的模型在追踪物体时，template是否都是固定不变，以一部影片作为输入，template是否都会一直是第一帧所标注的物体?
> 
> 是的
@botaoye 
你好，你的代码，https://github.com/botaoye/OSTrack/blob/33b5e12586216b7fd0e95d255bd01ba44cbec759/lib/test/tracker/ostrack.py#L76
以及 https://github.com/botaoye/OSTrack/blob/33b5e12586216b7fd0e95d255bd01ba44cbec759/lib/test/tracker/ostrack.py#L96
这里能看出来是更新了template了，不知道我的理解对不对
