### ISSUE TITLE
About training details

### ISSUE THREAD

**Issue by jackxiaolin** [botaoye/OSTrack#7]
Hello, you mentioned that the training time using 4 2080ti is about 23 hours. If  using a 3090, how long will the training time be? I expect 20 days during the reproduction process, is there anything wrong with that? Hope to be able to answer, thank you!

**Comment by AlexDotHam** [comment]
i though may be you don't use the cache?

**Comment by AlexDotHam** [comment]
Did you solve that problem? maybe my CPU is not good enough so the preprocess of data is slow than your repo qaq

**Comment by jackxiaolin** [comment]
> Did you solve that problem? maybe my CPU is not good enough so the preprocess of data is slow than your repo qaq

I think the long training time may be due to the following reasons: 1. I am using a single GPU, and the time may be double or more than that of multiple GPUs; 2, my training data set is stored in the mobile hard disk, if on the SSD may read the data will be much faster.
But compared to other algorithms, under the same conditions, I think this tracking algorithm is still very fast, and more epoches can be trained at the same time. So, if the above problem is solved, I think the training time may be shorter.

**Comment by jackxiaolin** [comment]
> 20 days is not normal. Perhaps you can provide more information such as your drive type (HHD or SSD) and part of your training log to determine the cause.

Thank you very much for your reply. I think my training time is too long may be due to the following reasons: 1. I train on a single GPU; 2. My dataset is stored on the mobile hard disk.
If I completed a full training according to such conditions, it would take a very long time, so I only trained 80 epoches. Among them, the test results of the weights of the 64th epoch have reached a very good level. This article is very inspiring to me as a novice, and I may continue to learn from the relevant ideas and carry out further work in the future. In addition, do you have other platforms or contact details to facilitate communication? Looking forward to hearing from you again!

**Comment by botaoye** [comment]
> Did you solve that problem? maybe my CPU is not good enough so the preprocess of data is slow than your repo qaq

In my experiments, CPU performance and disk read speed both seriously affect the training speed. Lmdb does not lead to an increase in training speed. The easiest way is to switch to a powerful CPU and SSD. Or you can try to implement the heavy data preprocessing steps with a GPU (Nvidia dali may help).

**Comment by botaoye** [comment]
> Thank you very much for your reply. I think my training time is too long may be due to the following reasons: 1. I train on a single GPU; 2. My dataset is stored on the mobile hard disk. If I completed a full training according to such conditions, it would take a very long time, so I only trained 80 epoches. Among them, the test results of the weights of the 64th epoch have reached a very good level. This article is very inspiring to me as a novice, and I may continue to learn from the relevant ideas and carry out further work in the future. In addition, do you have other platforms or contact details to facilitate communication? Looking forward to hearing from you again!

I'm glad to hear that. You can email me for my WeChat ID.

**Comment by jackxiaolin** [comment]
> > Thank you very much for your reply. I think my training time is too long may be due to the following reasons: 1. I train on a single GPU; 2. My dataset is stored on the mobile hard disk. If I completed a full training according to such conditions, it would take a very long time, so I only trained 80 epoches. Among them, the test results of the weights of the 64th epoch have reached a very good level. This article is very inspiring to me as a novice, and I may continue to learn from the relevant ideas and carry out further work in the future. In addition, do you have other platforms or contact details to facilitate communication? Looking forward to hearing from you again!
> 
> I'm glad to hear that. You can email me for my WeChat ID.
My WeChat ID is：yxlwuqiao2010，looking forward to contacting you very much.
