### ISSUE TITLE
OSTrack训练好的模型能够提供百度网盘的链接？

### ISSUE THREAD

**Issue by haoliyoupai09** [botaoye/OSTrack#75]

**Comment by botaoye** [comment]
不好意思回复的迟了。如果您依然需要的话麻烦再回复一下，我会上传百度云。

**Comment by haoliyoupai09** [comment]
已经下好了，多谢回复发自我的手机-------- 原始邮件 --------发件人： Botao Ye ***@***.***>日期： 2023年6月7日周三 晚上7:09收件人： botaoye/OSTrack ***@***.***>抄送： haoliyoupai09 ***@***.***>, Author ***@***.***>主    题： Re: [botaoye/OSTrack] OSTrack训练好的模型能够提供百度网盘的链接？ (Issue #75)
不好意思回复的迟了。如果您依然需要的话麻烦再回复一下，我会上传百度云。
