### ISSUE TITLE
关于GOT数据集下的训练和测试

### ISSUE THREAD

**Issue by HuibinT** [botaoye/OSTrack#79]
请问配置文件中的got10k_e100.yaml文件是用来干嘛的呢，是只为Got-10k数据集的测试而准备的训练配置文件吗？
我在e300.yaml的配置下训练的模型在got-10k数据集上测试的结果可以作为最终的实验结果吗？

**Comment by botaoye** [comment]
1. 是的
2. 因为GOT-10k test要求只使用GOT-10k 的 training set训练，所以需要使用got10k_e100.yaml作为最终的测试结果

**Comment by HuibinT** [comment]
好的，感谢您的解答
