### ISSUE TITLE
seq_ids那儿报exceed list range

### ISSUE THREAD

**Issue by Dinosaurcubs** [botaoye/OSTrack#84]
你好，麻烦问下单卡单GOT10K数据集训练时报exceed list of range 然后一直卡在加载预训练模型 这是啥情况？网上好像没有找到类似情况
这是我的训练指令： CUDA_VISIBLE_DEVICES=3 python tracking/train.py --script ostrack --config vitb_256_mae_ce_32x4_got10k_ep100 --save_dir ./output --mode single --nproc_per_node 4 --use_wandb 0

**Comment by jryxxx** [comment]
请问你怎么解决的

**Comment by Dinosaurcubs** [comment]
重装了下环境

**Comment by jryxxx** [comment]
谢谢
