### ISSUE TITLE
File ostrack384_elimination_ep300 missed

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [botaoye/OSTrack#86]
Hello, 

Would you please share the ostrack384_elimination_ep300 file ? I wanted to visualize candidate elimination process but this file is missed. 

Thanks in advance

**Comment by botaoye** [comment]
Hi, `ostrack384_elimination_ep300` should be `vitb_384_mae_ce_32x4_ep300`. I have modified the readme.

**Comment by MUHAMMEDZEYN** [comment]
Thanks a lot, it works now
