### ISSUE TITLE
Apply for customized videos

### ISSUE THREAD

**Issue by chenzhutian** [botaoye/OSTrack#9]
Hi! Thanks for sharing the repo!
I am wondering do you have any tips for applying your method to our own customized videos?
We are working on basketball videos and want to track players.
For each video, we have a few manually annotated GT.
We would like to fine-tune the model and apply the tracker on the videos.
Could you plz provide some pointers for doing this?

Thanks!

**Comment by botaoye** [comment]
1. To run OSTrack on customized videos with our pre-trained models, you can refer to [video_demo.py](https://github.com/botaoye/OSTrack/blob/main/tracking/video_demo.py) or implement your own evaluation datasets, which can refer to [got10kdataset.py](https://github.com/botaoye/OSTrack/blob/main/lib/test/evaluation/got10kdataset.py).
2. To fine-tune the model, you can create a customized training dataset (refer to [got10k.py](https://github.com/botaoye/OSTrack/blob/main/lib/train/dataset/got10k.py)) and modify `TRAIN.DATASETS_NAME` and `MODEL.PRETRAIN_FILE` to our pre-trained models in the config file.
