### ISSUE TITLE
is it possible to add new layers ?

### ISSUE THREAD

**Issue by FatihcanUslu** [botaoye/OSTrack#90]
I am trying to get a reliable confidence score, so i am trying to add cls_head layer (an MLP layer) from STARK repository. I am using vitb_256_mae_32x4_ep300. But i am getting missing key error since pretrained model doesnt have that information. so is there a way for update your OSTrack_ep0300.pth.tar model with those layers ? Also i am loading mae_pretrain_vit_base.pth. 

lib/model/ostrack/ostrack.py (changed made here):

    cls_head = MLP(256,256,1,3)
    model = OSTrack(
        backbone,
        box_head,
        aux_loss=False,
        head_type=cfg.MODEL.HEAD.TYPE,
        cls_head=cls_head,
    )
    
lib/train/trainers/base_trainer.py (error location):
       
         net.load_state_dict(checkpoint_dict[key])

error:
       
Training crashed at epoch -1
Traceback for the error!
Traceback (most recent call last):
  File "/home/pc2316/OSTrack/lib/train/../../lib/train/trainers/base_trainer.py", line 75, in train
    self.load_checkpoint()
  File "/home/pc2316/OSTrack/lib/train/../../lib/train/trainers/base_trainer.py", line 212, in load_checkpoint
    net.load_state_dict(checkpoint_dict[key])
  File "/home/pc2316/miniconda3/envs/ost/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OSTrack:
        Missing key(s) in state_dict: "cls_head.layers.0.weight", "cls_head.layers.0.bias", "cls_head.layers.1.weight", "cls_head.layers.1.bias", "cls_head.layers.2.weight", "cls_head.layers.2.bias".

**Comment by botaoye** [comment]
Just passing `strict=False` when calling `load_state_dict` can solve this problem.

**Comment by FatihcanUslu** [comment]
it worked thanks. I also tried giving dummy inputs for required layers to the checkpoint file and it also works.
